{
 "title": "Gateway Request",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "route_request", "label": "RouteRequest", "query": "gateway" },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "query_result(sum by (application)  (jvm_classes_loaded_classes{route_request=\"$route_request\"} offset 1m))"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(sum by (instance)  (jvm_classes_loaded_classes{route_request=\"$route_request\",application=\"$application\"} offset 1m))"
    }
   },
   {
    "name": "routeId",
    "label": "RouteId",
    "query": {
     "query": "label_values({route_request=\"$route_request\", application=\"$application\", instance=\"$instance\"},routeId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "application" },
  {
   "title": "Requestes [SUCCESS]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "irate(spring_cloud_gateway_requests_seconds_count{route_request=\"$route_request\",application=\"$application\",outcome=\"SUCCESSFUL\"}[5m])",
     "legendFormat": "[{{httpStatusCode}}] - route[{{routeId}}] - LB[{{routeUri}}]"
    }
   ]
  },
  {
   "title": "Requestes [FAIL]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "irate(spring_cloud_gateway_requests_seconds_count{route_request=\"$route_request\",application=\"$application\",outcome!~\"SUCCESSFUL\"}[5m])",
     "legendFormat": "[{{httpStatusCode}}] - route[{{routeId}}] - LB[{{routeUri}}] - [{{status}}]"
    }
   ]
  },
  { "title": "Instance Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Instance Requestes [SUCCESS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "irate(spring_cloud_gateway_requests_seconds_count{route_request=\"$route_request\",application=\"$application\",outcome=\"SUCCESSFUL\",instance=\"$instance\"}[5m])",
     "legendFormat": "[{{httpStatusCode}}] - route[{{routeId}}] - LB[{{routeUri}}]"
    }
   ]
  },
  {
   "title": "Instance Requestes [FAIL]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "irate(spring_cloud_gateway_requests_seconds_count{route_request=\"$route_request\",application=\"$application\",outcome!~\"SUCCESSFUL\",instance=\"$instance\"}[5m])",
     "legendFormat": "[{{httpStatusCode}}] - route[{{routeId}}] - LB[{{routeUri}}] - [{{status}}]"
    }
   ]
  },
  { "title": "Route Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "RouteRequestes [SUCCESS]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "irate(spring_cloud_gateway_requests_seconds_count{route_request=\"$route_request\",application=\"$application\",outcome=\"SUCCESSFUL\",instance=\"$instance\",routeId=\"$routeId\"}[5m])",
     "legendFormat": "[{{httpStatusCode}}] - route[{{routeId}}] - LB[{{routeUri}}]"
    }
   ]
  },
  {
   "title": "Route Requestes [FAIL]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "irate(spring_cloud_gateway_requests_seconds_count{route_request=\"$route_request\",application=\"$application\",outcome!~\"SUCCESSFUL\",instance=\"$instance\",routeId=\"$routeId\"}[5m])",
     "legendFormat": "[{{httpStatusCode}}] - route[{{routeId}}] - LB[{{routeUri}}] - [{{status}}]"
    }
   ]
  }
 ]
}